### ISSUE TITLE
Ready column does not reflect the actual state

### ISSUE THREAD

**Issue by vfarcic** [crossplane-contrib/provider-jet-azure#81]
While updating `KubernetesCluster`, the output of the `READY` column is `true` instead of `false`.

Output:

```
NAME                                                           READY   SYNCED   EXTERNAL-NAME
                                                         AGE
kubernetescluster.kubernetes.azure.tf.crossplane.io/ateamaks   True    True     /subscriptions/7f9f9b08-7d00-43c9-9d30-f10bb79e9a61/resourcegroups/ateamaks/provide
rs/Microsoft.ContainerService/managedClusters/ateamaks   44m
```

**Comment by ulucinar** [comment]
Hi @vfarcic,
Thank you very much for giving it a try, very much appreciated.
I tried reproducing this issue by adding a new tag to a `Ready` & `Sync`ed cluster object. My observation is that the object stays both `Ready` and `Sync`ed. My expectation was that although it would stay in `Ready` state (because we are adding a new tag, cluster is still ready), it would temporarily move to `Synced == False` state.

But I think with updating you mean some different kind of update that's expected to affect readiness of the cluster. Is this correct? I don't know exactly but for example updating control-plane version. What sort of update did you try with?

**Comment by vfarcic** [comment]
My bad. I thought that the `Ready` field would be `False` during, let's say, the process of upgrading the cluster. Now I understand that it's `Ready` if it's operational.
